py_library(
    name = "backend_lib",
    srcs = ["backend.py"],
    visibility = [
        "//pygatt/backends:__subpackages__",
        "//samples:__pkg__",
        "//tests:__subpackages__"
        ],
    deps = [],
)
